### ISSUE TITLE
Question about number of frames

### ISSUE THREAD

**Issue by Meta-AI-learner** [dk-kim/DFWSGAR#3]
Thanks for your  great work! I notice you set the number of frames during training as 5 for VD and 18 for NBA and use an uniform sampling strategy. I want to know if the number of frames has a significant influence on the performance, as setting 18 for NBA makes the training really slow. And i want to know the effect of sampling strategy in training.

Thanks!

**Comment by dk-kim** [comment]
In our experience, the effect of changing the number of frames are not critical. However, since we use three 1D convolution layer with receptive field 5 and no padding (time axis) for context aggregation module, more than 13 frames should be used or you should remove one or two 1D convolution layer. 
The purpose of segment-based sampling is to sample uniformly from entire video clip, but in our experience, uniform sampling also works well.

**Comment by Meta-AI-learner** [comment]
Thank you very much!
