### ISSUE TITLE
Question about the accuracy of volleyball dataset

### ISSUE THREAD

**Issue by 199943** [dk-kim/DFWSGAR#4]
First of all, thank you for the code. My experiments with the volleyball dataset show higher results for the base model than for Detector-Free, which has puzzled me for a long time. Have you tested the results of the base model for the volleyball dataset?

**Comment by dk-kim** [comment]
As stated in our paper, we test two settings for the Volleyball dataset, original setting (MCA) and merging set and pass class into pass-set class (merged MCA) which is proposed in Yan et al., ECCV 2020. In our experiment, base model performs well on merged MCA setting. In our thought since the most confusing classes pass and set classes are merged, base model also shows a good performance. Additionally, our proposed modules including motion-augmented feature extraction and partial context aggregation are more effective in the scenarios which are dynamic and requires long-term temporal modeling such as NBA dataset.

**Comment by 199943** [comment]
Thank you very much!
